@startuml

class Robot
{
  posX: int
  posY: int
}
class Camera
{
  posX: int
  posY: int
}
class CameraSystem
class User
class Graffity
{
  posX: int
  posY int
}
class Images


User - CameraSystem : start >
CameraSystem *- Camera : have 4  >
CameraSystem - Graffity : detect >
Camera <-> Robot : transmit coordinates 
Robot - Graffity : Cleaning >
Camera -down- Images : do >

@enduml
